---
version: "2"
services:
  
  # LDAP Server on
  ldap-host:
    image: "osixia/openldap:1.1.8"
    restart: always
    environment:
      LDAP_ORGANISATION: "ARNTS Labs"
      LDAP_DOMAIN: "${DOMAIN}"
      LDAP_ADMIN_PASSWORD: "${PASS}"
    volumes:
        - ${DATA}/ldap/db:/var/lib/ldap:rw
        - ${DATA}/ldap/config:/etc/ldap/slapd.d:rw
    ports:
      - "389:389/udp"
      - "389:389/tcp"
      - "636:636/udp"      
    hostname: ldap-host
  
  # LDAP Web GUI
  ldap-gui: 
    image: "osixia/phpldapadmin:0.6.12"
    links:
      - ldap-host
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-host
    ports:
      - "8080:80/tcp"
    hostname: ldap-gui

  # DNS/DHCP Server
  dhcpdns:
    image: "mayankt/dhcpdns"
    restart: always
    volumes:
        - ${DATA}/dhcpdns:/data:rw
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "67:67/udp"
      - "68:68/udp"
      - "8081:10000/tcp"
    hostname: dhcpdns

  # Guacamole services for Robust Backdoor access
  guac:
    image: db260179/guacamole-combined
    volumes:
      - ${DATA}/guac:/app/data:rw
    ports:
      - "8082:8080/tcp"
    hostname: guac
  
  # XenOrchestra service for Host communication
  xo:
    image: brijohn/xen-orchestra
    volumes:
      - ${DATA}/xo/redis:/var/lib/redis:rw
      - ${DATA}/xo/conf:/var/lib/xo-server:rw
    ports:
      - "8083:8000/tcp"
    hostname: xo

  # Simple Backend WebServers A and B
  webserver-a:
    image: mayankt/webserver:a
    restart: always
    ports:
      - "8084:80/tcp"
    hostname: webserver-a

  webserver-b:
    image: mayankt/webserver:b
    restart: always
    ports:
      - "8085:80/tcp"
    hostname: webserver-b

  #WebGoat for Application Firewall Demos
  webgoat:
    image: webgoat/webgoat-8.0
    restart: always
    ports:
      - "8086:8080/tcp"
    hostname: webgoat

  # Simple website to host files for easy download (particularly helpful storing cloud-init files) 
  cloud-drive:
    image: mayankt/config-drive
    restart: always
    volumes:
      - ${DATA}/cloud-drive:/www:rw
    ports:
      - "8087:80/tcp"
    hostname: config-drive
  
  # TFTP Service for network booting. 
  tftp:
    image: mayankt/pxe:rancheros
    restart: always
    volumes:
      - ${DATA}/tftp:/srv/tftp:rw
    ports:
      - "69:69/tcp"
      - "69:69/udp"
    hostname: tftp
  
  # Backdoor container or for remote sandbox environment with Docker tools
  backdoor:
    build:
      context: ./backdoor
      dockerfile: backdoor.dockerfile
    image: backdoor:sandbox
    privileged: true
    ports:
      - "222:22/tcp"
      - "9000-9010:9000-9010/tcp"
    volumes:
      - ~:/data

  # Docker Insecure Registry for local image storage
    # Docker registry service for DIND Backdoor environment
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
    volumes:
      - ${DATA}/registry:/data:rw
    hostname: registry