---
version: "2"
services:
  
  # LDAP Server on
  ldap-host:
    image: "osixia/openldap:1.1.8"
    restart: always
    environment:
      LDAP_ORGANISATION: "ARNTS Labs"
      LDAP_DOMAIN: "${DOMAIN}"
      LDAP_ADMIN_PASSWORD: "${PASS}"
    volumes:
        - ${LDAP_DB}:/var/lib/ldap:rw
        - ${LDAP_CONF}/ldap/config:/etc/ldap/slapd.d:rw
    networks:
      LAN:
        ipv4_address: "${NET}.22"
    hostname: ldap-host
  
  # LDAP Web GUI
  ldap-gui: 
    image: "osixia/phpldapadmin:0.6.12"
    links:
      - ldap-host
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-host
    networks:
      LAN:
        ipv4_address: "${NET}.23"
    hostname: ldap-gui

  # DNS/DHCP Server
  dhcpdns:
    image: "mayankt/dhcpdns"
    restart: always
    volumes:
        - ${DHCPDNS_DATA}:/data:rw
    networks:
      LAN:
        ipv4_address: "${NET}.24"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "67:67/udp"
      - "68:68/udp"
      - "10000:10000/tcp"
    hostname: dhcpdns

  # Guacamole services for Robust Backdoor access
  guac:
    image: db260179/guacamole-combined
    volumes:
      - ${GUAC_DATA}:/app/data:rw
    networks:
      LAN:
        ipv4_address: "${NET}.25"
    hostname: guac
  
  # XenOrchestra service for Host communication
  xo:
    image: brijohn/xen-orchestra
    volumes:
      - ${REDIS_DATA}:/var/lib/redis:rw
      - ${XO_DATA}:/var/lib/xo-server:rw
    networks:
      LAN:
        ipv4_address: "${NET}.26"
    hostname: xo

  # Simple Backend WebServers A and B
  webserver-a:
    image: mayankt/webserver:a
    restart: always
    networks:
      LAN:
        ipv4_address: "${NET}.27"
    hostname: webserver-a

  webserver-b:
    image: mayankt/webserver:b
    restart: always
    networks:
        LAN:
          ipv4_address: "${NET}.28"
    hostname: webserver-b

  #WebGoat for Application Firewall Demos
  webgoat:
    image: webgoat/webgoat-8.0
    restart: always
    networks:
      LAN:
        ipv4_address: "${NET}.29"
    hostname: webgoat

  # Simple website to host files for easy download (particularly helpful storing cloud-init files) 
  cloud-drive:
    image: mayankt/config-drive
    restart: always
    volumes:
      - ${CLOUD_DRIVE}:/www:rw
    networks:
      LAN:
        ipv4_address: "${NET}.30"
    hostname: config-drive
  
  # TFTP Service for network booting. 
  tftp:
    image: mayankt/pxe:rancheros
    restart: always
    volumes:
      - ${TFTP_DATA}:/srv/tftp:rw
    networks:
      LAN:
        ipv4_address: "${NET}.31"
    hostname: tftp

# Defined networks
networks:
  # define a host-external network
  LAN:
    driver: macvlan
    driver_opts:
      parent: "${ETH}"
    ipam:
      config:
        - subnet: "${NET}.0/24"
          gateway: "${GATEWAY}"
          ip_range: "${NET}.35/28" # IP from this pool are assigned automatically 